import test from 'node:test';import assert from 'node:assert/strict';
import {CONFIG,initialState,makeForest,rasterRoots} from '../src/scenario.js';
import {stepCPU,totals,drag,exchange} from '../src/physics.js';
const c={...CONFIG,nx:24,ny:16,dx:.6};const roots=new Float32Array(c.nx*c.ny*4);const closed={boundary:false,sediment:false,vegetation:false};
function flat(depth=1){const s=initialState(c);for(let i=0;i<s.length;i+=12){s[i]=depth;s[i+1]=s[i+2]=0;s[i+3]=depth*.12;s[i+4]=s[i+7]=-depth;}return s;}
test('lake at rest over irregular bed: no spurious motion',()=>{let s=initialState(c);const original=s.slice();for(let k=0;k<100;k++)s=stepCPU(s,roots,c,closed);assert.ok(Math.max(...s.filter((_,i)=>i%12===1||i%12===2).map(Math.abs))<1e-5);assert.ok(Math.abs(totals(s,c).water-totals(original,c).water)<1e-5);});
test('closed dam break conserves water and advected sediment; nonnegative',()=>{let s=flat();for(let z=0;z<c.ny;z++)for(let x=0;x<c.nx/2;x++){s[(z*c.nx+x)*12]=1.3;s[(z*c.nx+x)*12+3]=.3;}const before=totals(s,c);for(let k=0;k<300;k++)s=stepCPU(s,roots,c,closed);const after=totals(s,c);assert.ok(after.finite&&after.minH>=0&&after.minMs>=0);assert.ok(Math.abs(after.water/before.water-1)<1e-5);assert.ok(Math.abs(after.sediment/before.sediment-1)<1e-5);});
test('quadratic drag is dissipative and matches analytic decay',()=>{const q=drag(2,0,1,.5,2,1.2);assert.ok(Math.abs(q[0]-2/(1+.5*1.2*.5*2*2))<1e-12);assert.equal(q[1],0);assert.deepEqual(drag(2,-1,1,0,2),[2,-1]);});
test('settling matches exponential and exchanges exactly equal mass',()=>{const e=exchange(1,-1,-1,0,1,10,c);assert.ok(Math.abs(e.ms-Math.exp(-c.settling*10))<1e-12);assert.ok(Math.abs(e.ms+(e.bed+1)*c.rhoBulk-1)<1e-10);});
test('erosion stops at hard bottom; no sediment created without stock',()=>{assert.ok(exchange(0,-1.45,-1,10,1,100,c).e<1e-10);assert.equal(exchange(0,-1,-1,0,1,100,c).d,0);});
test('suspended plus bed mass conserved through 1000 exchange steps',()=>{let s=flat(),before=totals(s,c);for(let k=0;k<1000;k++)s=stepCPU(s,roots,c,{...closed,sediment:true});const after=totals(s,c);assert.ok(Math.abs(after.sediment-before.sediment)<.01);assert.ok(after.minMs>=0);});
test('root raster area invariant under grid refinement',()=>{const f=makeForest(),r=rasterRoots(f.segments),c2={...CONFIG,nx:240,ny:160,dx:.3},r2=rasterRoots(f.segments,c2);const area=a=>a.reduce((x,y)=>x+y,0);assert.ok(Math.abs(area(r)*.36/(area(r2)*.09)-1)<.02);assert.ok(r.some(x=>x>0));});
test('with drag disabled, paired simulations are identical',()=>{let a=flat(),b=a.slice();for(let k=0;k<30;k++){a=stepCPU(a,roots,c,{time:k*c.dt,vegetation:false});b=stepCPU(b,roots,c,{time:k*c.dt,vegetation:false});}assert.deepEqual(a,b);});

test('vegetation changes momentum without changing local water or sediment mass',()=>{const a=flat();for(let i=0;i<a.length;i+=12)a[i+1]=.25;const root=new Float32Array(c.nx*c.ny*4).fill(.3);const no=stepCPU(a,root,c,{...closed,vegetation:false});const yes=stepCPU(a,root,c,{...closed,vegetation:true});for(let i=0;i<a.length;i+=12){assert.equal(yes[i],no[i]);assert.equal(yes[i+3],no[i+3]);assert.ok(Math.abs(yes[i+1])<=Math.abs(no[i+1]));}assert.ok(yes[12*100+1]<no[12*100+1]);});
test('increasing frontal area strictly strengthens momentum dissipation',()=>{const values=[0,.1,.5,2].map(area=>drag(.3,.1,.5,area,.018,CONFIG.cd*CONFIG.vegetationDragMultiplier));for(let i=1;i<values.length;i++)assert.ok(Math.hypot(...values[i])<Math.hypot(...values[i-1]));});
test('sediment pulse is transported in the water-flow direction',()=>{let s=flat();for(let i=0;i<s.length;i+=12){s[i+1]=.2;s[i+3]=0;}s[(8*c.nx+8)*12+3]=1;const out=stepCPU(s,roots,c,closed);assert.ok(out[(8*c.nx+9)*12+3]>0);assert.ok(out[(8*c.nx+8)*12+3]<1);const sum=a=>a.filter((_,i)=>i%12===3).reduce((a,b)=>a+b,0);assert.ok(Math.abs(sum(out)-sum(s))<1e-6);});
test('display-only terrain multiplier does not mutate physical state',async()=>{const {visualBed}=await import('../src/observations.js');const state=flat(),copy=state.slice();state[4]+=.004;copy[4]+=.004;for(const multiplier of [1,3,5,10,25,50])assert.ok(Math.abs(visualBed(state[4],state[7],multiplier)-(state[7]+(state[4]-state[7])*multiplier))<1e-12);assert.deepEqual(state,copy);assert.deepEqual(stepCPU(state,roots,c,closed),stepCPU(copy,roots,c,closed));});
test('restoration layout has 192 trees spanning a wider forest',()=>{const f=makeForest('restoration').trees;assert.equal(f.length,192);assert.ok(Math.max(...f.map(t=>t.x))-Math.min(...f.map(t=>t.x))>19);});
