import {CONFIG,initialState} from './scenario.js';
export class Simulation {
 static async create(device,roots,c=CONFIG){const self=new Simulation();self.device=device;self.c=c;self.roots=roots;self.time=0;const shader=await(await fetch('./shaders/physics.wgsl')).text();const module=device.createShaderModule({code:shader});const errors=(await module.getCompilationInfo()).messages.filter(m=>m.type==='error');if(errors.length)throw Error(errors.map(m=>m.message).join('\n'));self.pipeline=await device.createComputePipelineAsync({layout:'auto',compute:{module,entryPoint:'main'}});self.rootBuffer=device.createBuffer({size:roots.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(self.rootBuffer,0,roots);self.params=[0,1].map(()=>device.createBuffer({size:80,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}));self.states=[0,1].map(()=>[0,1].map(()=>device.createBuffer({size:c.nx*c.ny*48,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC|GPUBufferUsage.COPY_DST})));self.groups=self.states.map((pair,caseID)=>pair.map((buffer,phase)=>device.createBindGroup({layout:self.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer}},{binding:1,resource:{buffer:pair[1-phase]}},{binding:2,resource:{buffer:self.rootBuffer}},{binding:3,resource:{buffer:self.params[caseID]}}]})));self.phase=0;self.reset();return self;}
 reset(tide=0){this.visual?.reset();this.time=0;this.phase=0;this.initial=initialState(this.c,tide);for(const pair of this.states)for(const b of pair)this.device.queue.writeBuffer(b,0,this.initial);}
 paramsData(options,time,caseID){const c=this.c;return new Float32Array([c.nx,c.ny,c.dx,options.dt??c.dt,time,options.wave??.18,options.tide??0,c.period,(options.vegetation??(caseID===0))?1:0,options.boundary===false?0:1,options.sediment===false?0:1,0,c.friction,c.cd*(c.vegetationDragMultiplier??1),c.rhoBulk,c.tauE,c.erosion,c.settling,c.tauD,c.concentration]);}
 // Distinct queue writes/submissions preserve per-step forcing time. Both cases
 // receive exactly the same forcing, dt, and number of steps.
 step(count,options={}){const d=this.device;for(let k=0;k<count;k++){for(let a=0;a<2;a++)d.queue.writeBuffer(this.params[a],0,this.paramsData(options,this.time,a));const encoder=d.createCommandEncoder();const pass=encoder.beginComputePass();pass.setPipeline(this.pipeline);for(let a=0;a<2;a++){pass.setBindGroup(0,this.groups[a][this.phase]);pass.dispatchWorkgroups(Math.ceil(this.c.nx/8),Math.ceil(this.c.ny/8));}pass.end();this.visual?.step(encoder,1-this.phase,options.dt??this.c.dt,this.time);d.queue.submit([encoder.finish()]);this.phase=1-this.phase;this.time+=options.dt??this.c.dt;}}
 current(a){return this.states[a][this.phase];}
 async read(a){const d=this.device,b=d.createBuffer({size:this.c.nx*this.c.ny*48,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const en=d.createCommandEncoder();en.copyBufferToBuffer(this.current(a),0,b,0,b.size);d.queue.submit([en.finish()]);await b.mapAsync(GPUMapMode.READ);const data=new Float32Array(b.getMappedRange().slice(0));b.unmap();b.destroy();return data;}
 dispose(){this.visual?.dispose();for(const pairs of this.states)for(const b of pairs)b.destroy();for(const b of this.params)b.destroy();this.rootBuffer.destroy();}
}
