import {CONFIG,BANDS} from './scenario.js';
// Independent CPU reference for small-grid verification of the GPU path.
// State: [h,qx,qz,hC, zb, accumulatedD, accumulatedE, initialZb,
//         boundaryWater,boundarySediment,positivityWaterCorrection, reserved].
export function face(a,b,axis,c=CONFIG){const top=Math.max(a[4],b[4]);const ha=Math.max(0,a[4]+a[0]-top),hb=Math.max(0,b[4]+b[0]-top);const qa=a[0]>c.dry?[a[1]*ha/a[0],a[2]*ha/a[0]]:[0,0],qb=b[0]>c.dry?[b[1]*hb/b[0],b[2]*hb/b[0]]:[0,0];const ua=ha>c.dry?qa[axis]/ha:0,ub=hb>c.dry?qb[axis]/hb:0;const speed=Math.max(Math.abs(ua)+Math.sqrt(c.g*ha),Math.abs(ub)+Math.sqrt(c.g*hb));const flux=[.5*(qa[axis]+qb[axis])-.5*speed*(hb-ha),.5*(qa[0]*ua+qb[0]*ub)-.5*speed*(qb[0]-qa[0]),.5*(qa[1]*ua+qb[1]*ub)-.5*speed*(qb[1]-qa[1]),0];flux[axis+1]+=.25*c.g*(ha*ha+hb*hb);const donor=flux[0]>=0?a:b;flux[3]=flux[0]*(donor[0]>c.dry?donor[3]/donor[0]:0);return {flux,ha,hb};}
export function drag(qx,qz,h,area,dt,cd=CONFIG.cd){const v=Math.hypot(qx,qz)/Math.max(h,CONFIG.dry),factor=1+.5*cd*area/Math.max(h,CONFIG.dry)*v*dt;return [qx/factor,qz/factor];}
export function exchange(ms,bed,initialBed,tau,h,dt,c=CONFIG){const available=Math.max(0,(bed-initialBed+.45)*c.rhoBulk);const e=Math.min(available,c.erosion*Math.max(tau/c.tauE-1,0)*dt);const rate=c.settling*Math.max(1-tau/c.tauD,0)/Math.max(h,c.dry);const d=(ms+e)*(1-Math.exp(-rate*dt));return {ms:ms+e-d,bed:bed+(d-e)/c.rhoBulk,d,e};}
export function stepCPU(input,roots,c=CONFIG,{time=0,wave=.18,tide=0,vegetation=true,boundary=true,sediment=true}={}){const out=new Float32Array(input.length),get=(x,z)=>{const xx=Math.max(0,Math.min(c.nx-1,x)),zz=Math.max(0,Math.min(c.ny-1,z));const a=Array.from(input.subarray((zz*c.nx+xx)*12,(zz*c.nx+xx)*12+12));if(x<0||x>=c.nx)a[1]*=-1;if(z<0||z>=c.ny)a[2]*=-1;return a;};for(let z=0;z<c.ny;z++)for(let x=0;x<c.nx;x++){const id=z*c.nx+x,i=id*12,a=get(x,z),e=face(a,get(x+1,z),0,c),w=face(get(x-1,z),a,0,c),n=face(a,get(x,z+1),1,c),s=face(get(x,z-1),a,1,c);let h=a[0]-c.dt/c.dx*(e.flux[0]-w.flux[0]+n.flux[0]-s.flux[0]);let qx=a[1]-c.dt/c.dx*(e.flux[1]-w.flux[1]+n.flux[1]-s.flux[1]+.5*c.g*(w.hb*w.hb-e.ha*e.ha));let qz=a[2]-c.dt/c.dx*(e.flux[2]-w.flux[2]+n.flux[2]-s.flux[2]+.5*c.g*(s.hb*s.hb-n.ha*n.ha));let ms=a[3]-c.dt/c.dx*(e.flux[3]-w.flux[3]+n.flux[3]-s.flux[3]);const b=a.slice();b[10]+=Math.max(0,-h);b[11]+=Math.max(0,-ms);h=Math.max(h,0);ms=Math.max(ms,0);
if(h>c.dry){const velocity=Math.hypot(qx,qz)/h;const f=1+c.dt*c.friction*velocity/h;qx/=f;qz/=f;let area=0;for(let k=0;k<4;k++){const low=a[7]+BANDS[k],high=a[7]+BANDS[k+1];area+=(roots[id*4+k]||0)*Math.max(0,Math.min(a[4]+h,high)-Math.max(a[4],low))/(high-low);}if(vegetation)[qx,qz]=drag(qx,qz,h,area,c.dt,c.cd*(c.vegetationDragMultiplier??1));}else{qx=0;qz=0;}
if(boundary&&x<8){const blend=1-Math.exp(-c.dt*2*((8-x)/8)**2),ramp=Math.min(1,time/12),eta=tide+wave*ramp*Math.sin(2*Math.PI*time/c.period),target=Math.max(0,eta-a[4]),targetQ=wave*ramp*Math.sin(2*Math.PI*time/c.period)*Math.sqrt(c.g*Math.max(tide-a[4],.1));const hNew=h+(target-h)*blend,msNew=ms+(target*c.concentration-ms)*blend;b[8]+=hNew-h;b[9]+=msNew-ms;h=hNew;ms=msNew;qx+=(targetQ-qx)*blend;qz*=1-blend;}
if(sediment&&x>=10){const tau=h>c.dry?1000*c.friction*(qx*qx+qz*qz)/(h*h):0;const ex=exchange(ms,a[4],a[7],tau,h,c.dt,c);ms=ex.ms;b[5]+=ex.d;b[6]+=ex.e;b[4]=a[7]+(b[5]-b[6])/c.rhoBulk;}
b[0]=h;b[1]=qx;b[2]=qz;b[3]=ms;out.set(b,i);}return out;}
export function totals(state,c=CONFIG){let water=0,sediment=0,boundaryWater=0,boundarySediment=0,correction=0,sedimentCorrection=0,minH=Infinity,minMs=Infinity,maxVelocity=0;for(let i=0;i<state.length;i+=12){water+=state[i];sediment+=state[i+3]+(state[i+4]-state[i+7]+.45)*c.rhoBulk;boundaryWater+=state[i+8];boundarySediment+=state[i+9];correction+=state[i+10];sedimentCorrection+=state[i+11];minH=Math.min(minH,state[i]);minMs=Math.min(minMs,state[i+3]);if(state[i]>c.dry)maxVelocity=Math.max(maxVelocity,Math.hypot(state[i+1],state[i+2])/state[i]);}const a=c.dx*c.dx;return {water:water*a,sediment:sediment*a,boundaryWater:boundaryWater*a,boundarySediment:boundarySediment*a,correction:correction*a,sedimentCorrection:sedimentCorrection*a,minH,minMs,maxVelocity,finite:state.every(Number.isFinite)};}
